apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pavk230/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: http://identity
            - name: NEXT_PUBLIC_SALARY_API_URL
              value: http://salary
            - name: NEXT_PUBLIC_VOTE_API_PROXY_PATH
              value: http://vote
            - name: NEXT_PUBLIC_SEARCH_API_PROXY_PATH
              value: http://search
            - name: NEXT_PUBLIC_STATS_API_URL
              value: http://stats
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP