apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityservice
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      containers:
        - name: identityservice
          image: kithusshand/identityservice
          ports:
            - containerPort: 5100
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5100

            # 🔥 THIS IS THE REAL FIX
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=identity_db;Username=admin;Password=password123
