apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/api/Auth(.*)$ /api/auth$1 last;
      rewrite ^/api/Salary(.*)$ /api/salary$1 last;
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /api/Auth
            pathType: Prefix
            backend:
              service:
                name: identityservice
                port:
                  number: 80
          - path: /api/salary
            pathType: Prefix
            backend:
              service:
                name: salaryservice
                port:
                  number: 80
          - path: /api/Salary
            pathType: Prefix
            backend:
              service:
                name: salaryservice
                port:
                  number: 80
