# salary.yaml (Deployment version for testing)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: salaryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salaryservice
  template:
    metadata:
      labels:
        app: salaryservice
    spec:
      containers:
        - name: salaryservice
          image: kithusshand/salaryservice
          env:
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: password123
            - name: DB_NAME
              value: paymentappdb   # ✅ must match postgres
