name: SearchService Docker Build & Push

on:
  push:
    branches:
      - production_pravini
    paths:
      - "SearchService.Api/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_PRAVINI }}
          password: ${{ secrets.DOCKER_PASSWORD_PRAVINI }}

      - name: Build and Push SearchService
        uses: docker/build-push-action@v5
        with:
          context: ./SearchService.Api
          dockerfile: ./SearchService.Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME_PRAVINI }}/searchservice:latest
            ${{ secrets.DOCKER_USERNAME_PRAVINI }}/searchservice:${{ github.sha }}